name: "CD: Release"

on:
  push:
    tags:
      - "v*"

jobs:
  continuous-deployment-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Create a release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
